theme: jekyll-theme-cayman


title: Gustavo Pereira
description: a (PHP) Web Developer... to infinity and beyond!


twitter_username:     gustavosteam
github_username:      gustavoper
linkedin_username:    gustavoperphp
speakerdeck_username: gustavoper